spring:
  jmx:
    enabled: false
  profiles:
    active: receiver,ssl

hono:
  client:
    host: 10.180.29.64
    username: consumer@HONO
    password: verysecret
    reconnectAttempts: 5

tenant:
  id: DEFAULT_TENANT
device:
  id: 4711

---

spring:
  profiles: receiver
hono:
  client:
    port: 15671

---

spring:
  profiles: ssl
hono:
  client:
    hostnameVerificationRequired: false
    trustStorePath: target/config/hono-demo-certs-jar/trusted-certs.pem
